# Generated by Django 5.0.6 on 2024-07-15 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OtherTables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='custom_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Universities'),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='OtherTables.course'),
        ),
    ]
